remote_theme: mmistakes/minimal-mistakes
plugins:
- jekyll-remote-theme
- jekyll-include-cache

title: mrdavidkendall
description: a few thoughts and ideas that I wanted to write down somewhere
logo: /assets/img/logo.png
